[2025-05-28T05:28:01.109+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-28T05:28:01.145+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: global_street_food_analysis_dag.run_street_food_analysis manual__2025-05-28T05:22:38.546586+00:00 [queued]>
[2025-05-28T05:28:01.162+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: global_street_food_analysis_dag.run_street_food_analysis manual__2025-05-28T05:22:38.546586+00:00 [queued]>
[2025-05-28T05:28:01.162+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2025-05-28T05:28:01.198+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): run_street_food_analysis> on 2025-05-28 05:22:38.546586+00:00
[2025-05-28T05:28:01.207+0000] {standard_task_runner.py:72} INFO - Started process 869 to run task
[2025-05-28T05:28:01.213+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'global_street_food_analysis_dag', 'run_street_food_analysis', 'manual__2025-05-28T05:22:38.546586+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/global_food.py', '--cfg-path', '/tmp/tmpt_v76p_1']
[2025-05-28T05:28:01.216+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask run_street_food_analysis
[2025-05-28T05:28:01.363+0000] {task_command.py:467} INFO - Running <TaskInstance: global_street_food_analysis_dag.run_street_food_analysis manual__2025-05-28T05:22:38.546586+00:00 [running]> on host 6041824b4dd1
[2025-05-28T05:28:01.758+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='global_street_food_analysis_dag' AIRFLOW_CTX_TASK_ID='run_street_food_analysis' AIRFLOW_CTX_EXECUTION_DATE='2025-05-28T05:22:38.546586+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-28T05:22:38.546586+00:00'
[2025-05-28T05:28:01.763+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-28T05:28:01.889+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-28T05:28:01.906+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit /opt/airflow/scripts/food.py']
[2025-05-28T05:28:01.953+0000] {subprocess.py:86} INFO - Output:
[2025-05-28T05:28:02.263+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2025-05-28T05:28:02.274+0000] {process_utils.py:132} INFO - Sending 15 to group 869. PIDs of all processes in the group: [871, 873, 874, 869]
[2025-05-28T05:28:02.875+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 869
[2025-05-28T05:28:02.876+0000] {taskinstance.py:3083} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-28T05:28:02.876+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-05-28T05:28:02.889+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=873, status='terminated', started='05:28:01') (873) terminated with exit code None
[2025-05-28T05:28:03.431+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=874, status='terminated', started='05:28:01') (874) terminated with exit code None
[2025-05-28T05:28:03.092+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 240, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3085, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-05-28T05:28:03.866+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=global_street_food_analysis_dag, task_id=run_street_food_analysis, run_id=manual__2025-05-28T05:22:38.546586+00:00, execution_date=20250528T052238, start_date=20250528T052801, end_date=20250528T052803
[2025-05-28T05:28:04.275+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-28T05:28:04.413+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=869, status='terminated', exitcode=2, started='05:28:00') (869) terminated with exit code 2
[2025-05-28T05:28:04.414+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=871, status='terminated', started='05:28:01') (871) terminated with exit code None
[2025-05-28T05:28:04.414+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 143
[2025-05-28T05:28:04.530+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-28T05:28:06.020+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
