[2025-05-30T05:19:21.781+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-30T05:19:21.805+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_csv_sum_dag.read_and_sum_csv scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-05-30T05:19:21.815+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_csv_sum_dag.read_and_sum_csv scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-05-30T05:19:21.815+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-30T05:19:21.827+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): read_and_sum_csv> on 2024-01-01 00:00:00+00:00
[2025-05-30T05:19:21.835+0000] {standard_task_runner.py:72} INFO - Started process 204 to run task
[2025-05-30T05:19:21.879+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'read_csv_sum_dag', 'read_and_sum_csv', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/read_csv_sum_dag.py', '--cfg-path', '/tmp/tmpxr21aoc8']
[2025-05-30T05:19:21.899+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask read_and_sum_csv
[2025-05-30T05:19:22.014+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-30T05:19:22.244+0000] {task_command.py:467} INFO - Running <TaskInstance: read_csv_sum_dag.read_and_sum_csv scheduled__2024-01-01T00:00:00+00:00 [running]> on host 1232a4f48263
[2025-05-30T05:19:22.245+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:449 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-30T05:19:22.486+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_csv_sum_dag' AIRFLOW_CTX_TASK_ID='read_and_sum_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-05-30T05:19:22.501+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-30T05:19:22.584+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/read_csv_sum_dag.py", line 11, in read_and_sum
    df = pd.read_csv(csv_path)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mooli\\OneDrive\\Documents\\Sum.csv'
[2025-05-30T05:19:22.607+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=read_csv_sum_dag, task_id=read_and_sum_csv, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20250530T051921, end_date=20250530T051922
[2025-05-30T05:19:22.629+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-30T05:19:22.630+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task read_and_sum_csv ([Errno 2] No such file or directory: 'C:\\Users\\mooli\\OneDrive\\Documents\\Sum.csv'; 204)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/read_csv_sum_dag.py", line 11, in read_and_sum
    df = pd.read_csv(csv_path)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mooli\\OneDrive\\Documents\\Sum.csv'
[2025-05-30T05:19:22.650+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-05-30T05:19:22.670+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-30T05:19:22.672+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2025-05-30T05:29:00.286+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-30T05:29:00.302+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_csv_sum_dag.read_and_sum_csv scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-05-30T05:29:00.310+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_csv_sum_dag.read_and_sum_csv scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-05-30T05:29:00.311+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-30T05:29:00.321+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): read_and_sum_csv> on 2024-01-01 00:00:00+00:00
[2025-05-30T05:29:00.327+0000] {standard_task_runner.py:72} INFO - Started process 225 to run task
[2025-05-30T05:29:00.332+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'read_csv_sum_dag', 'read_and_sum_csv', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/read_csv_sum_dag.py', '--cfg-path', '/tmp/tmpkua6n9a2']
[2025-05-30T05:29:00.335+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask read_and_sum_csv
[2025-05-30T05:29:00.354+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-30T05:29:00.387+0000] {task_command.py:467} INFO - Running <TaskInstance: read_csv_sum_dag.read_and_sum_csv scheduled__2024-01-01T00:00:00+00:00 [running]> on host 1232a4f48263
[2025-05-30T05:29:00.388+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:449 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-30T05:29:00.462+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_csv_sum_dag' AIRFLOW_CTX_TASK_ID='read_and_sum_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-05-30T05:29:00.463+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-30T05:29:00.516+0000] {read_csv_sum_dag.py:11} INFO - Columns in CSV: ['Unnamed: 0', 'Sumextension', 'EmpCode']
[2025-05-30T05:29:00.520+0000] {read_csv_sum_dag.py:19} ERROR - Column 'your_column_name' not found in CSV
[2025-05-30T05:29:00.520+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-30T05:29:00.531+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-30T05:29:00.532+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=read_csv_sum_dag, task_id=read_and_sum_csv, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20250530T052900, end_date=20250530T052900
[2025-05-30T05:29:00.587+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-05-30T05:29:00.603+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-30T05:29:00.605+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
